### ISSUE TITLE
error - placing paired electric pole

### ISSUE THREAD

**Issue by judos** [Simcra/Surfaces#6]
(Factorio 0.13.15)
When placing an paired electric power pole I get the following error:

```
Error while running event on_tick (ID 0)
LuaEntity belongs to surface surfacesmod_cavern_1 (index 1) but a LuaEntity belonging to surface nauvis (index 0) was expected.
stack traceback:
    __Surfaces__/script/lib/api.lua:147: in function 'connect_neighbour'
    __Surfaces__/script/lib/pair-util.lua:111: in function 'finalize_paired_entity'
    __Surfaces__/script/events.lua:259: in function '?'
    __Surfaces__/script/events.lua:40: in function 'on_tick'
    __Surfaces__/control.lua:171: in function <__Surfaces__/control.lua:171>
```

There is currently nothing we can do about this. Factorio just doesn't let you connect the power cable among different surfaces. Strangely enough it still works for red and green signal cables...
I will post a bug in Factorio forum...

**Comment by judos** [comment]
[Bug report on factorio forum](https://forums.factorio.com/viewtopic.php?f=7&t=30651)

**Comment by judos** [comment]
So the bug in factorio is not a bug since it is not intended to connect power poles of different surface anymore. That means a different approach is needed. E.g. The Factorissimo uses accumulators to share energy from one surface to a different one.

**Comment by Simcra** [comment]
Removed old electric pole entities and replaced with new accumulators, sorry for lack of comments till now, have been really busy.

**Comment by judos** [comment]
Hey one day response is perfect! Thanks for the great mod by the way 👍🏻
Too bad that when standing one surface above ground it's not possible to see the ground structures... 😅

**Comment by Simcra** [comment]
if you're not too busy do you reckon you could test 0.0.7 for me and let me know if you find any more errors.
