### ISSUE TITLE
migration issue - get killed during migration

### ISSUE THREAD

**Issue by judos** [Simcra/Surfaces#7]
I just installed 0.0.7 and the migration for my cavern is started and I actually get killed during this when I get teleported into a large biter nest :D
Is there a way to make the character immortal during this migration?

/edit: trying again with a spawned in mk2 power suit with 3 fusion generators and 1950 points of shield capacity

**Comment by judos** [comment]
Unluckily migration still doesn't work. The game freezes after about half of the screen on the map is "migrated".
I'm attaching the savegame:
[j1-withSurfaces7.zip](https://github.com/Simcra/Surfaces/files/409893/j1-withSurfaces7.zip)

**Comment by Simcra** [comment]
try downloading the version from releases or the mod portal again, migrations do work, we tested them last night, they just take awhile.

**Comment by judos** [comment]
I'm I tried again and let factorio run for a while. After all it did complete the migration for the cavern_1 surface (even so factorio went up to using 12GiB of RAM). Maybe there's some problem somewhere.
But hey no worries about this migration, after all it's 0.0.7 version :)
Thanks for the help!
