### ISSUE TITLE
error - load game when surfaces is not installed before 0.0.7

### ISSUE THREAD

**Issue by judos** [Simcra/Surfaces#8]
I tried to load a map where surfaces was not installed from before and got this:

`Error while running the on_configuration_changed: __Surfaces__/control.lua:119: bad argument #1 to 'gmatch' (string expected, got nil)`

Because surfaces was not installed before the var here is nil:
`local ver = _config_data["mod_changes"]["Surfaces"]["old_version"]`

so to fix it I simply added a nil check then I can load the map.

**Comment by Simcra** [comment]
fixed in newest release, see github code.

**Comment by Simcra** [comment]
will update mod portal release later today.
